config/routes.rb
RubyBB::Application.routes.draw do

  root :to => 'forums#index'

  resources :topics do
    member do
      put 'pin' => :pin
    end
  end

  resources :forums do
    collection do
      put 'position' => :position
    end
  end

  as :user do
    get 'register' => 'devise/registrations#new', :as => :new_user_registration
    post 'profile' => 'devise/registrations#create', :as => :user_registration
    delete 'profile' => 'devise/registrations#destroy', :as => :user_registration
    get 'profile' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'profile' => 'registrations#update', :as => :user_registration
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  devise_for :users, :skip => [:sessions, :registrations]

  resources :users, :only => [:index, :show] do
    member do
      put 'roles' => :roles
      put 'bot' => :bot
    end
  end

  resources :messages

  resources :small_messages, :only => [:create, :destroy]

  resources :follows, :only => [:index, :create, :destroy]

  resources :notifications, :only => [:index, :destroy] do
    collection do
      delete '' => :clear
    end
  end
  resources :bookmarks, :only => :index do
    collection do
      delete '' => :clear
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks
  include Spammable

  acts_as_paranoid

  PER_PAGE = 20
  paginates_per PER_PAGE

  has_many :notifications, :dependent => :destroy
  has_many :small_messages, :dependent => :destroy
  has_many :follows, :as => :followable, :dependent => :destroy
  belongs_to :updater, :class_name => 'User', :foreign_key => 'updater_id'
  belongs_to :user, :counter_cache => true
  belongs_to :topic, :counter_cache => true, :touch => true
  belongs_to :forum, :counter_cache => true, :touch => true
  validates :content, :presence => true, :length => { :maximum => 32768 }
  attr_accessible :content, :topic_id

  scope :with_follows, lambda { |user| select('follows.id as follow_id').joins("LEFT JOIN follows ON followable_id = messages.id AND followable_type = 'Message' AND follows.user_id = #{user.try(:id)}") if user }

  scope :followed_by, lambda { |user| select('follows.id as follow_id').joins("JOIN follows ON followable_id = messages.id AND followable_type = 'Message' AND follows.user_id = #{user.try(:id)}") if user }

  mapping do
    indexes :id, :index => :not_analyzed
    indexes :content, :analyzer => 'snowball'
    indexes :topic, :as => 'topic.try(:name)', :analyzer => 'snowball'
    indexes :user, :as => 'user.try(:name)', :analyzer => 'snowball'
    indexes :at, :as => 'created_at', :type => 'date'
  end

  before_save :render_content
  after_save :fire_notifications

  after_create :update_parents, :autofollow
  after_destroy :decrement_parent_counters

  private
  def autofollow
    Follow.find_or_create_by_followable_type_and_followable_id_and_user_id('Topic', topic_id, user_id)
  end

  def update_parents
    topic.update_column :last_message_id, id
    topic.update_column :updater_id, user_id
    forum.update_column :updater_id, user_id
    if forum.parent_id
      Forum.update_counters forum.parent_id, messages_count: 1
    end
  end

  def decrement_parent_counters
    if forum.parent_id
      Forum.update_counters forum.parent_id, messages_count: -1
    end
  end

  def render_content
    @user_ids = Array.new
    require 'redcarpet'
    renderer = Redcarpet::Render::HTML.new link_attributes: {rel: 'nofollow', target: '_blank'}, filter_html: true
    extensions = {space_after_headers: true, no_intra_emphasis: true, tables: true, fenced_code_blocks: true, autolink: true, strikethrough: true, superscript: true}
    hashtagged = self.content.gsub(/(^|\s)@([[:alnum:]_-]+)/u) { |tag|
      if user = User.where(name: $2).first
        @user_ids << user.id
        "#{$1}[@#{$2}](#{Rails.application.routes.url_helpers.user_path(user)})"
      else
        tag
      end
    }.gsub(/(^|\s)#([[:alnum:]_-]+)/u) { |tag|
      "#{$1}[##{$2}](#{Rails.application.routes.url_helpers.messages_path(q: $2)})"
    }
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    self.rendered_content = redcarpet.render(hashtagged)
  end

  def fire_notifications
    @user_ids.each do |uid|
      if uid != self.user_id
        Notification.find_or_create_by_user_id_and_message_id(uid, self.id).touch
      end
    end
    Follow.not_by(self.user_id).where(:followable_id => self.user_id, :followable_type => 'User').each do |f|
      Notification.find_or_create_by_user_id_and_message_id(f.user_id, self.id).touch
    end
    Follow.not_by(self.user_id).where(:followable_id => self.topic_id, :followable_type => 'Topic').each do |f|
      Notification.find_or_create_by_user_id_and_message_id(f.user_id, self.id).touch
    end
    if self.topic.messages_count == 0
      Follow.not_by(self.user_id).where(:followable_id => self.forum_id, :followable_type => 'Forum').each do |f|
        Notification.find_or_create_by_user_id_and_message_id(f.user_id, self.id).touch
      end
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  authorize_resource
  before_filter :authenticate_user!

  # GET /messages
  # GET /messages.json
  def index
    @meta = true
    begin
      p = params
      @messages = Message.search(page: params[:page], load: { include: [:user, :topic, :updater, :small_messages => :user]}) do
        query { string p[:q], default_operator: 'AND' }
        sort { by :at, 'desc' }
      end
    rescue
      flash[:error] = I18n.t('search.error')
      @messages = []
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new topic_id: params[:topic_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])
    @message.user_id = current_user.id
    @message.forum_id = Topic.find(params[:message][:topic_id]).forum_id

    respond_to do |format|
      if @message.save
        format.html { redirect_to topic_url(@message.topic, page: Topic.find(@message.topic_id).messages.page.num_pages, anchor: "m#{@message.id}"), notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])
    @message.updater_id = current_user.id

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to topic_url(@message.topic, page: params[:page]), notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    if(@message == @message.topic.messages.first)
      r = forum_url(@message.forum)
      @message.topic.destroy
    else
      r = topic_url(@message.topic, page: params[:page])
      @message.destroy
    end

    respond_to do |format|
      format.html { redirect_to r }
      format.json { head :no_content }
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.haml
= simple_form_for(@message, :url => @message.new_record? ? messages_path(:page => params[:page]) : message_path(@message, :page => params[:page]), :defaults => {:input_html => {:class => 'input-xxlarge'}}, :html => {:class => 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :content, :required => true, :input_html => {:rows => 15, :class => 'input-xxlarge markdown-toolbar'}
    = f.input :topic_id, :as => :hidden

  .form-actions
    = f.button :submit, class: @message.new_record? || @message.user_id == current_user.id ? 'btn-primary' : 'btn-warning'
    = link_to t('common.destroy'), message_path(@message, page: params[:page]), method: :delete, class: 'btn btn-danger', data: { confirm: t('common.are_you_sure') } if !@message.new_record? && can?(:destroy, @message)
    = link_to t('common.back'), topic_path(@message.topic, page: params[:page]), :class => 'btn btn-link' unless defined?(back) and !back

app/views/messages/_list.html.haml
:javascript
  var values = #{@messages.map(&:user).uniq.reject{|u|!u}.map{|u|{val:u.name}}.to_json};

- if @messages.any?
  = paginate @messages

  %table.table.table-striped.messages
    %tr.hidden
      %th= t('activerecord.models.user')
      %th= t('activerecord.models.message')
    - @messages.each do |message|
      %tr{class: @folded ? 'folded' : nil}
        %td.user
          %a{name: "m#{message.id}"}
          %p= username message.user
          %p
            = render 'shared/avatar', user: message.user, size: 100
          %p.action= link_to t('common.edit'), edit_message_path(message, page: params[:page]) if can? :update, message
        %td
          - if @meta
            .meta
              %p.search= link_to message.topic.name, topic_path(message.topic)
          .message{ class: cycle('odd', 'even') }
            = raw message.rendered_content
            - if message.user && !message.user.human?
              - if can?(:bot, message.user)
                = form_for message.user, url: bot_user_path(message.user, topic_id: message.topic_id) do |f|
                  = f.submit t('.bot', name: message.user.name), name: 'bot', class: 'btn btn-danger'
                  = f.submit t('.human', name: message.user.name), name: 'human', class: 'btn btn-success'
              - elsif message.user_id == current_user.id
                %p
                  %em= t('.i_am_a_bot')
              - else
                %p
                  %em= t('.it_is_a_bot')
          .meta
            - if message.updater && (message.updater_id != message.user_id || message.updated_at - 5.minutes > message.created_at)
              %p.date= t('.updated_by', name: message.updater.name, date: l(message.updated_at))
            .small_messages
              - message.small_messages.each do |small_message|
                = render 'small_messages/show', small_message: small_message
              - if can? :create, SmallMessage.new.tap{|s| s.forum_id = message.forum_id}
                = simple_form_for SmallMessage.new(message_id: message.id), remote: true, html: { id: "new_small_message-#{message.id}" } do |f|
                  = f.input :content
                  = f.input :message_id, as: :hidden
        %td.ago.hidden-portrait-phone.meta
          - if url_for == notifications_path
            %p= link_to t('common.remove'), notification_path(message.notification_id), method: :delete, rel: :nofollow, remote: true, class: 'delete_notification'
          %p{title: l(message.created_at)}= time_ago_in_words message.created_at
          - if current_user && !params[:q] && current_user.id != message.user_id
            = render 'follows/show', id: message.follow_id, followable_id: message.id, followable_type: 'Message'

  = paginate @messages
- else
  .no_results= t('search.no_results')

app/views/messages/edit.html.haml
%h1 Editing message

= render 'topics/breadcrumb', topic: @message.topic, buttons: false

= render 'form'

app/views/messages/index.html.haml
%h1= t('.title')

= render 'list'

app/views/messages/new.html.haml
%h1 New message

= render 'topics/breadcrumb', topic: @message.topic, buttons: false

= render 'form'

app/views/messages/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @message.content
%p
  %b User:
  = @message.user
%p
  %b Topic:
  = @message.topic
%p
  %b Forum:
  = @message.forum

= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path