config/routes.rb
RubyBB::Application.routes.draw do

  root :to => 'forums#index'

  resources :topics do
    member do
      put 'pin' => :pin
    end
  end

  resources :forums do
    collection do
      put 'position' => :position
    end
  end

  as :user do
    get 'register' => 'devise/registrations#new', :as => :new_user_registration
    post 'profile' => 'devise/registrations#create', :as => :user_registration
    delete 'profile' => 'devise/registrations#destroy', :as => :user_registration
    get 'profile' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'profile' => 'registrations#update', :as => :user_registration
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  devise_for :users, :skip => [:sessions, :registrations]

  resources :users, :only => [:index, :show] do
    member do
      put 'roles' => :roles
      put 'bot' => :bot
    end
  end

  resources :messages

  resources :small_messages, :only => [:create, :destroy]

  resources :follows, :only => [:index, :create, :destroy]

  resources :notifications, :only => [:index, :destroy] do
    collection do
      delete '' => :clear
    end
  end
  resources :bookmarks, :only => :index do
    collection do
      delete '' => :clear
    end
  end

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  include Redirectable

  default_scope order(:position, :parent_id, :slug)

  extend FriendlyId
  friendly_id :name, use: :slugged

  acts_as_paranoid
  has_many :children, :class_name => 'Forum', :foreign_key => 'parent_id'
  belongs_to :parent, :class_name => 'Forum', :foreign_key => 'parent_id'
  has_many :topics, :dependent => :destroy
  has_many :roles, :dependent => :destroy
  has_many :follows, :as => :followable, :dependent => :destroy
  belongs_to :updater, :class_name => 'User', :foreign_key => 'updater_id'
  validates :name, :presence => true, :length => { :maximum => 64 }, :uniqueness => { :case_sensitive => false }
  validates :content, :length => { :maximum => 32768 }

  scope :with_follows, lambda { |user| select('follows.id as follow_id').joins("LEFT JOIN follows ON followable_id = forums.id AND followable_type = 'Forum' AND follows.user_id = #{user.try(:id)}") if user }

  attr_accessible :content, :name, :parent_id

  def fix_counters
    topics = Topic.where(:forum_id => children.map(&:id) << id).count
    messages = Message.where(:forum_id => children.map(&:id) << id).count
    Forum.update_counters id, topics_count: topics - topics_count, messages_count: messages - messages_count
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  authorize_resource
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :get_stats, :only => :index

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.includes(:updater, :children, :roles => :user).where(:parent_id => nil)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @forums }
    end
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
    begin
      @forum = Forum.select('forums.*').with_follows(current_user).includes(:children).find(params[:id])
    rescue
      if r = Redirection.where(redirectable_type: 'Forum', slug: params[:id]).first
        return redirect_to r.redirectable, :status => :moved_permanently
      else
        render_404
      end
    end

    @topics = Topic.select('topics.*').includes(:user, :updater).for_user(current_user).where(:forum_id => @forum.children.map(&:id) << @forum.id).order('topics.pinned desc, topics.updated_at desc').page(params[:page])
    @topics = @topics.includes(:forum) if @forum.children.any?

    @pinnable = true
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @forum }
    end
  end

  # GET /forums/new
  # GET /forums/new.json
  def new
    @forum = Forum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @forum }
    end
  end

  # GET /forums/1/edit
  def edit
    @forum = Forum.find(params[:id])
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(params[:forum])
    if @forum.parent_id
      @forum.position = @forum.parent.position
      @forum.parent.touch
    end

    respond_to do |format|
      if @forum.save
        format.html { redirect_to forums_url, notice: 'Forum was successfully created.' }
        format.json { render json: @forum, status: :created, location: @forum }
      else
        format.html { render action: "new" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /forums/position
  def position
    i = 1
    params[:forums].each do |f|
      if f.present?
        f = Forum.find(f.to_i)
        f.update_column :position, i
        f.children.update_all :position => i
        i = i + 1
      end
    end

    respond_to do |format|
      format.html { redirect_to forums_url }
      format.json { head :no_content }
    end
  end

  # PUT /forums/1
  # PUT /forums/1.json
  def update
    @forum = Forum.find(params[:id])

    respond_to do |format|
      if @forum.update_attributes(params[:forum])
        format.html { redirect_to forums_url, notice: 'Forum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy

    respond_to do |format|
      format.html { redirect_to forums_url }
      format.json { head :no_content }
    end
  end

  private
  def get_stats
    @users = User.where('updated_at >= ?', 5.minutes.ago)
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_breadcrumb.html.haml
- if buttons
  = link_to t('.new_topic'), new_topic_path(forum_id: forum.id), class: 'btn in-breadcrumb' if can? :create, Topic.new(forum_id: forum.id)

  - if current_user
    = render 'follows/show', id: forum.follow_id, followable_id: forum.id, followable_type: 'Forum'

%ul.breadcrumb
  %li
    = link_to t('common.title'), root_path
    %span.divider /
  %li.active
    = link_to forum.name, forum_path(forum)

app/views/forums/_form.html.haml
= simple_form_for(@forum, :defaults => {:input_html => {:class => 'input-xxlarge'}}, :html => {:class => 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, :required => true, :input_html => {:maxlength => 64}
    = f.association :parent
    = f.input :content, :input_html => {:rows => 5}

  .form-actions
    = f.button :submit, class: 'btn-warning'
    = link_to t('common.destroy'), @forum, method: :delete, class: 'btn btn-danger', data: { confirm: t('common.are_you_sure') } if !@forum.new_record? && can?(:destroy, @forum)
    = link_to t('common.back'), @forum.new_record? ? forums_path : forum_path(@forum), :class => 'btn btn-link'

app/views/forums/edit.html.haml
%h1 Editing forum

= render 'breadcrumb', forum: @forum, buttons: false

= render 'form'

app/views/forums/index.html.haml
%h1
  = t('common.title')

%table.table.table-striped{id: can?(:position, Forum) ? 'forums' : nil}
  %thead
    %tr
      - if can? :position, Forum.new
        %th.icons
      %th
        = t('.title')
        %small= link_to t('common.new'), new_forum_path if can? :create, Forum.new
      %th.hidden-phone
      %th.hidden-portrait-phone
  %tbody
    - @forums.each do |forum|
      %tr{id: forum.id}
        - if can? :position, forum
          %td.position
            ☰
        - cache "forum-#{forum.id}-#{forum.updated_at}" do
          %td
            = link_to forum do
              %p.title
                %strong= forum.name
            - if forum.children.any?
              %p
                = t('.see_also')
                =raw forum.children.map{|f| link_to f.name, forum_path(f)}.join(', ')
            %p.reset= forum.content
            - if forum.roles.any?
              %small
                = "#{t('common.staff')}:"
                = raw forum.roles.where(name: %w[admin moderator]).map{|r| username(r.user)}.join(', ');
          %td.infos.hidden-phone
            %p= t('common.topics_count', count: forum.topics_count)
            %p= t('common.messages_count', count: forum.messages_count)
          %td.infos.hidden-portrait-phone
            - if forum.updated_at
              %p= l forum.updated_at, format: :short
              %p
                = t('common.by')
                = username forum.updater

.widget
  %h4= t('common.stats')
  %p= t('.counters', topics: Topic.count, messages: Message.count)
  %p
    = "#{t('.users', count: User.count)}#{t('.online', count: @users.count)}"
    = raw @users.map{|u| username u}.join(', ')

app/views/forums/new.html.haml
%h1 New forum

= render 'form'

app/views/forums/show.html.haml
-# cache "forum-#{@forum.id}-topics-page#{params[:page]}-#{current_user.try(:role, @forum.id)||'anon'}-#{@forum.updated_at}" do
- if true

  - content_for :title, @forum.name

  %h1
    = t('.title', name: @forum.name)
    %small= link_to t('common.edit'), edit_forum_path(@forum) if can? :update, @forum

  = render 'breadcrumb', forum: @forum, buttons: true

  = render 'topics/list'

  = render 'breadcrumb', forum: @forum, buttons: true