config/routes.rb
RubyBB::Application.routes.draw do

  root :to => 'forums#index'

  resources :topics do
    member do
      put 'pin' => :pin
    end
  end

  resources :forums do
    collection do
      put 'position' => :position
    end
  end

  as :user do
    get 'register' => 'devise/registrations#new', :as => :new_user_registration
    post 'profile' => 'devise/registrations#create', :as => :user_registration
    delete 'profile' => 'devise/registrations#destroy', :as => :user_registration
    get 'profile' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'profile' => 'registrations#update', :as => :user_registration
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  devise_for :users, :skip => [:sessions, :registrations]

  resources :users, :only => [:index, :show] do
    member do
      put 'roles' => :roles
      put 'bot' => :bot
    end
  end

  resources :messages

  resources :small_messages, :only => [:create, :destroy]

  resources :follows, :only => [:index, :create, :destroy]

  resources :notifications, :only => [:index, :destroy] do
    collection do
      delete '' => :clear
    end
  end
  resources :bookmarks, :only => :index do
    collection do
      delete '' => :clear
    end
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include Redirectable

  extend FriendlyId
  friendly_id :name, use: :slugged

  acts_as_paranoid
  paginates_per 25

  belongs_to :viewer, :class_name => 'User', :foreign_key => 'viewer_id'
  belongs_to :updater, :class_name => 'User', :foreign_key => 'updater_id'
  belongs_to :last_message, :class_name => 'Message', :foreign_key => 'last_message_id'
  belongs_to :user, :counter_cache => true
  belongs_to :forum, :counter_cache => true, :touch => true
  has_many :messages, :include => [:user], :dependent => :destroy
  has_many :follows, :as => :followable, :dependent => :destroy
  accepts_nested_attributes_for :messages
  validates :name, :presence => true, :length => { :maximum => 64 }, :uniqueness => { :scope => :forum_id, :case_sensitive => false }
  validates :forum, :presence => true
  attr_accessible :name, :forum_id, :messages_attributes

  has_many :bookmarks, :dependent => :destroy
  scope :for_user, lambda { |user| select('bookmarks.message_id as bookmarked_id').joins("LEFT JOIN bookmarks ON bookmarks.topic_id = topics.id AND bookmarks.user_id = #{user.try(:id)}") if user }

  scope :only_for_user, lambda { |user| select('bookmarks.message_id as bookmarked_id').joins("JOIN bookmarks ON bookmarks.topic_id = topics.id AND bookmarks.message_id < topics.last_message_id AND bookmarks.user_id = #{user.try(:id)}") if user }

  scope :with_follows, lambda { |user| select('follows.id as follow_id').joins("LEFT JOIN follows ON followable_id = topics.id AND followable_type = 'Topic' AND follows.user_id = #{user.try(:id)}") if user }

  scope :followed_by, lambda { |user| select('follows.id as follow_id').joins("JOIN follows ON followable_id = topics.id AND followable_type = 'Topic' AND follows.user_id = #{user.try(:id)}") if user }

  after_update :update_counters
  after_create :increment_parent_counters, :autofollow
  after_destroy :decrement_parent_counters

  def last_page
    (messages_count.to_f / Message::PER_PAGE).ceil
  end

  def last_page? page
    last_page == (page||1).to_i
  end

  private
  def autofollow
    f = Follow.new(followable_id: id, followable_type: 'Topic')
    f.user_id = user_id
    f.save
  end

  def increment_parent_counters
    if forum.parent_id
      Forum.update_counters forum.parent_id, topics_count: 1
    end
  end

  def decrement_parent_counters
    if forum.parent_id
      Forum.update_counters forum.parent_id, topics_count: -1
    end
  end

  def update_counters
    if forum_id_changed?
      messages.update_all forum_id: forum_id
      was = Forum.find(forum_id_was)
      if was.parent_id != forum.id && was.id != forum.parent_id
        Forum.update_counters forum_id_was, topics_count: -1, messages_count: -messages_count
        Forum.update_counters forum_id, topics_count: 1, messages_count: messages_count
      end
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  authorize_resource
  before_filter :authenticate_user!, :except => [:show]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    begin
      @topic = Topic.select('topics.*').with_follows(current_user).find(params[:id])
    rescue
      if r = Redirection.where(redirectable_type: 'Topic', slug: params[:id]).first
        return redirect_to r.redirectable, :status => :moved_permanently
      else
        render_404
      end
    end

    if params.has_key? :newest
      m_id = current_user.bookmarks.where(topic_id: @topic.id).first.message_id
      nb = Message.where(topic_id: @topic.id).where('id <= ?', m_id).count
      page = (nb.to_f / Message::PER_PAGE).ceil
      return redirect_to topic_url(@topic, page: page > 1 ? page : nil, anchor: "m#{m_id}")
    end

    @messages = @topic.messages.select('messages.*').includes(:user, :updater, :small_messages => :user).with_follows(current_user).page params[:page]
    @message = Message.new topic_id: @topic.id
    @message.forum_id = @topic.forum_id

    if current_user
      b = current_user.bookmarks.find_or_initialize_by_topic_id(@topic.id)
      b.message_id = @topic.last_message_id
      b.save!
    end

    if current_user && current_user.id != @topic.viewer_id && @topic.last_page?(params[:page])
      @topic.update_column :viewer_id, current_user.id
      @topic.update_column :views_count, @topic.views_count+1
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new forum_id: params[:forum_id]
    @topic.messages.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.includes(:forum => :children).find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])
    @topic.user_id = current_user.id
    @topic.updater_id = current_user.id
    message = @topic.messages.first
    message.user_id = current_user.id
    message.forum_id = params[:topic][:forum_id]

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1/pin
  def pin
    @topic = Topic.find(params[:id])
    @topic.update_column :pinned, !@topic.pinned
    respond_to do |format|
      format.html { redirect_to forum_url(@topic.forum), notice: 'Topic was successfully updated.' }
      format.json { head :no_content }
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    params[:topic].delete :messages_attributes
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to topic_url(@topic), notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    forum = @topic.forum
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to forum_url(forum) }
      format.json { head :no_content }
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_breadcrumb.html.haml
- if current_user && buttons
  = render 'follows/show', id: topic.follow_id, followable_id: topic.id, followable_type: 'Topic'

%ul.breadcrumb
  %li
    = link_to t('common.title'), root_path
    %span.divider /
  %li
    = link_to topic.forum.name, forum_path(topic.forum)
    %span.divider /
  %li.active= link_to topic.name, topic_path(topic)

app/views/topics/_form.html.haml
= simple_form_for(@topic, :defaults => {:input_html => {:class => 'input-xxlarge'}}, :html => {:class => 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, :required => true, :input_html => {:maxlength => 64}
    - if @topic.new_record?
      - if @topic.forum.children.any?
        = f.association :forum, :collection => Forum.where(:id => @topic.forum.children.map(&:id) << @topic.forum_id), :include_blank => false
      -else
        .hidden= f.association :forum
      = f.simple_fields_for :messages do |m|
        = m.input :content, :input_html => {:rows => 15, :class => 'input-xxlarge markdown-toolbar'}
    - else
      = f.association :forum, :include_blank => false

  .form-actions
    = f.button :submit, class: @topic.new_record? || @topic.user_id == current_user.id ? 'btn-primary' : 'btn-warning'
    = link_to t('common.destroy'), @topic, method: :delete, class: 'btn btn-danger', data: { confirm: t('common.are_you_sure') } if !@topic.new_record? && can?(:destroy, @topic)
    = link_to t('common.back'), @topic.new_record? ? forum_path(@topic.forum) : topic_path(@topic), :class => 'btn btn-link'

app/views/topics/_list.html.haml
- if @topics.any?
  = paginate @topics

  %table.table.table-striped.topics{class: @folded ? 'table-condensed' : nil}
    %tr
      - if @pinnable
        %th.icons
      %th= t('.topics')
      %th.number.hidden-phone= t('.messages')
      %th.number.hidden-phone= t('.views')
      %th.hidden-portrait-phone= t('.last')
    - pinned = false
    - @topics.each do |topic|
      %tr{class: "#{pinned && !topic.pinned && @pinnable ? 'separator' : nil} #{@folded ? 'folded' : nil}"}
        - if @pinnable
          - if can?(:pin, topic)
            %td
              - if topic.pinned
                = link_to pin_topic_path(topic), method: 'put', title: t('common.unpin') do
                  %i.icon-circle-arrow-right
              - else
                = link_to pin_topic_path(topic), method: 'put', title: t('common.pin_on') do
                  %i.icon-arrow-up
          - else
            %td
              - if topic.pinned
                %i.icon-circle-arrow-right{ title: t('common.pinned') }
        %td
          - if current_user && topic.bookmarked_id && topic.bookmarked_id < topic.last_message_id
            = link_to topic_path(topic) + "?newest" do
              %p.title
                %i.icon-bookmark{title: t('.new_messages')}
                = topic.name
          - else
            = link_to topic do
              %p.title= topic.name
          - unless @folded
            %p
              - if @forum && topic.forum_id != @forum.id
                = t('common.in')
                = link_to topic.forum.name, forum_path(topic.forum)
              = t('common.by')
              = username topic.user
              - if topic.messages_count > 20
                –
                = link_to t('.last_page'), topic_path(topic, page: topic.last_page)
        %td.number.hidden-phone
          %p= topic.messages_count
        %td.number.hidden-phone
          %p= topic.views_count
        %td.infos.hidden-portrait-phone
          - if topic.messages.any?
            %p= l topic.updated_at, format: :short
            - unless @folded
              %p
                = t('common.by')
                = username topic.updater
      - pinned = topic.pinned

  = paginate @topics
- else
  .no_results= t('search.no_results')

app/views/topics/edit.html.haml
%h1 Editing topic

= render 'breadcrumb', topic: @topic, buttons: false

= render 'form'

app/views/topics/index.html.haml
%h1 Listing topics

%table
  %tr
    %th Name
    %th User
    %th Forum
    %th Messages count
    %th
    %th
    %th

  - @topics.each do |topic|
    %tr
      %td= topic.name
      %td= topic.user
      %td= topic.forum
      %td= topic.messages_count
      %td= link_to 'Show', topic
      %td= link_to 'Edit', edit_topic_path(topic)
      %td= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Topic', new_topic_path

app/views/topics/new.html.haml
%h1 New topic

= render 'forums/breadcrumb', forum: @topic.forum, buttons: false

= render 'form'

app/views/topics/show.html.haml
-# " cache "topic-#{@topic.id}-messages-page#{params[:page]}-#{current_user.try(:role, @topic.forum_id)||'anon'}-#{@topic.updated_at}" do
- if true

  - content_for :title, @topic.name

  %h1
    = t('.title', name: @topic.name)
    %small= link_to t('common.edit'), edit_topic_path(@topic) if can? :update, @topic

  = render 'breadcrumb', topic: @topic, buttons: true

  = render 'messages/list'

  = render 'breadcrumb', topic: @topic, buttons: true

  = render 'messages/form', back: false if can? :create, @message