config/routes.rb
RubyBB::Application.routes.draw do

  root :to => 'forums#index'

  resources :topics do
    member do
      put 'pin' => :pin
    end
  end

  resources :forums do
    collection do
      put 'position' => :position
    end
  end

  as :user do
    get 'register' => 'devise/registrations#new', :as => :new_user_registration
    post 'profile' => 'devise/registrations#create', :as => :user_registration
    delete 'profile' => 'devise/registrations#destroy', :as => :user_registration
    get 'profile' => 'devise/registrations#edit', :as => :edit_user_registration
    put 'profile' => 'registrations#update', :as => :user_registration
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  devise_for :users, :skip => [:sessions, :registrations]

  resources :users, :only => [:index, :show] do
    member do
      put 'roles' => :roles
      put 'bot' => :bot
    end
  end

  resources :messages

  resources :small_messages, :only => [:create, :destroy]

  resources :follows, :only => [:index, :create, :destroy]

  resources :notifications, :only => [:index, :destroy] do
    collection do
      delete '' => :clear
    end
  end
  resources :bookmarks, :only => :index do
    collection do
      delete '' => :clear
    end
  end

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    -#
      %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
        %a.close{"data-dismiss" => "alert"} &#215;
        = content_tag :div, msg, :id => "flash_#{name}"
    = js add_gritter(msg, :image => name == :notice ? "success" : "error", :title => name == :notice ? "Success" : "Error")

app/views/layouts/_navigation.html.haml
%a.btn.btn-navbar{data: {toggle: 'collapse', target: '.nav-collapse'}}
  .icon-bar
  .icon-bar
  .icon-bar
= link_to t('common.title'), root_path, :class => 'brand'
.nav-collapse
  %ul.nav
    %li= link_to t('.users'), users_path
    - if user_signed_in?
      %li= link_to t('.user'), user_path(current_user)
      %li= link_to t('.follows'), follows_path
      %li
        = link_to notifications_path do
          = t('.notifications')
          %span.badge.badge-success#faye-notifications{class: current_user.notifications_count <= 0 && 'hidden'}= current_user.notifications_count
      -# %li= link_to t('.bookmarks'), bookmarks_path
      %li= link_to t('.logout'), destroy_user_session_path, :method=>'delete'
    - else
      %li= link_to t('.sign_up'), new_user_registration_path
      %li= link_to t('.login'), new_user_session_path
  = render 'layouts/search'

app/views/layouts/_search.html.haml
= form_tag messages_path, method: :get, class: 'form-search navbar-form' do
  = text_field_tag :q, params[:q], placeholder: t('search.title'), class: 'search-query'
  = submit_tag t('search.find'), name: nil, class: 'hidden'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? "#{yield(:title)} - #{t('common.title')}" : t('common.title')
    %meta{:content => t('common.description'), :name => "description"}
    %meta{:content => "Julien Grillot", :name => "author"}
    = favicon_link_tag '/ruby.png', rel: 'image_src', :type => 'image/png'
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "//#{request.host}:9292/faye.js"
    = csrf_meta_tags
    = yield(:head)
    - if current_user
      :javascript
        function link_to(text, href){ return '<a href="'+href+'">'+text+'</a>'; }
        $(document).ready(function() {
          client = new Faye.Client(location.protocol + '//' + location.hostname + ':9292/faye');
          $notifications = $('#faye-notifications');
          client.subscribe('/#{current_user.id}/notifications', function(data) {
            $notifications.html(parseInt($notifications.html())+1);
            $notifications.removeClass('hidden');
            $.gritter.add({title: data.title, text: data.content + ' ' + link_to('#{t('common.read')}', data.link), image: data.avatar});
          });
        });
  %body
    %header.navbar
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            - if @widgets_mode
              = render 'layouts/messages'
              = yield
            - else
              .span12
                = render 'layouts/messages'
                = yield
          %footer
            © 2012
            = link_to 'RubyBB', 'http://www.rubybb.com'
            –
            = link_to 'Fork me on GitHub', 'https://github.com/RubyBB/RubyBB'
            –
            = link_to '@RubyBB_dev', 'https://twitter.com/RubyBB_dev'
            –
            = link_to 'Share on Facebook', "https://www.facebook.com/sharer/sharer.php?u=#{u request.url}", rel: 'nofollow'